### ISSUE TITLE
Doesn't work after Safari 15 update

### ISSUE THREAD

**Issue by AndreyZaslavskiyWMG** [rmatec/aws-account-switcher-safari-extension#4]
Configuration is fine, while dropdown menu contains 0 profiles to switch.

**Comment by parkeyparker** [comment]
I've got a working fork/branch here: https://github.com/SourceCube-Ltd/aws-account-switcher-safari-extension/tree/update-2.2.0
Problem is you'll have to build it locally in Xcode yourself. I've not looked closely enough yet to see what would be required to open a PR but based on some of the previous commits to this repo I am guessing Apple weren't happy about the donations stuff so I doubt they will take kindly to the "supporters" stuff that v2.2.0 of the original plugin includes. I'd need to spend more time stripping that out and then I'd need to make sure my Xcode settings align with this repo in order to get the PR to not have conflicts. For the same reason I also can't publish to the App Store as there is already a version there.
Also worth noting that to get this to build you will need to make sure that rollup is installed globally with `npm install -g rollup`

**Comment by michaelm-88** [comment]
@parkeyparker  which version is on App Store ? can you send the link plz

**Comment by parkeyparker** [comment]
@michaelm-88 I never even looked at the App Store version due to the open issues saying it wasn't working and set to updating it instead... The link in the README is https://apps.apple.com/gb/app/aws-account-switcher/id1535264792?mt=12 however it's not available in my region apparently. @rmatec are you likely to update the App Store version any time soon or should I look to publish my own copy?

**Comment by aficustree** [comment]
@parkeyparker , I'm trying to build and after installing rollup in the global scope xcodebuild come back with

```
[!] Error: Could not resolve './lib/storage_repository.js' from aws-account-switcher-safari-extension/Resources/src/options.js
Error: Could not resolve './lib/storage_repository.js' from aws-account-switcher-safari-extension/Resources/src/options.js
    at error (/opt/homebrew/lib/node_modules/rollup/dist/shared/rollup.js:158:30)
    at ModuleLoader.handleResolveId (/opt/homebrew/lib/node_modules/rollup/dist/shared/rollup.js:22263:24)
    at /opt/homebrew/lib/node_modules/rollup/dist/shared/rollup.js:22257:26
```

I don't see that file in the repo, curious what I'm doing wrong.

**Comment by parkeyparker** [comment]
@aficustree apologies, there was a .gitignore which was ignoring `src/` and `js/` which I have now removed as most of the files already existed so it served no real purpose. I've just amended and force pushed my commit so hopefully it will now work for you. Apologies for the confusion!

**Comment by parkeyparker** [comment]
@michaelm-88 if you are still after an app store version it can now be found here: https://apps.apple.com/gb/app/aws-extend-switch-roles/id1592710340 Works on both MacOS and iOS
